name: Deploy with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: project  # Ensures GitHub fetches secrets from 'project' environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file from secrets
        run: |
        
          echo "BACKEND_PORT=${{ secrets.BACKEND_PORT }}" >> .env
      

      - name: Debug .env (show keys only, hide values)
        run: |
          echo "Environment variables loaded:"
          cut -d "=" -f1 .env

   
