name: Build and Push Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: project  # Make sure your secrets are in this environment
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env from secrets
        run: |
    
          echo "BACKEND_HOST=${{ vars.BACKEND_HOST }}" >> .env
      

      - name: Show .env (testing only)
        run: cat .env
