name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Debug secrets
        run: |
          echo "MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}"
          echo "MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}"
          echo "MYSQL_USER: ${{ secrets.MYSQL_USER }}"
          echo "MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}"

      - name: Show MySQL logs if failure
        if: failure()
        run: |
          echo "=== MySQL Logs ==="
          docker logs mysql
