name: Deploy with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
      BACKEND_HOST: ${{ secrets.BACKEND_HOST }}
      FRONTEND_PORT: ${{ secrets.FRONTEND_PORT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file from secrets
        run: |
          echo "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}" >> .env
          echo "MYSQL_USER=${MYSQL_USER}" >> .env
          echo "MYSQL_PASSWORD=${MYSQL_PASSWORD}" >> .env
          echo "MYSQL_DATABASE=${MYSQL_DATABASE}" >> .env
          echo "BACKEND_PORT=${BACKEND_PORT}" >> .env
          echo "BACKEND_HOST=${BACKEND_HOST}" >> .env
          echo "FRONTEND_PORT=${FRONTEND_PORT}" >> .env

      
