name: Deploy with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: project  # Fetches secrets & vars from the 'project' environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file from environment secrets/vars
        run: |
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
          echo "MYSQL_DATABASE=${{ vars.MYSQL_DATABASE }}" >> .env
          
          echo "BACKEND_PORT=${{ vars.BACKEND_PORT }}" >> .env
          echo "BACKEND_HOST=${{ vars.BACKEND_HOST }}" >> .env
          echo "FRONTEND_PORT=${{ vars.FRONTEND_PORT }}" >> .env

      - name: Debug .env (keys only, no secrets)
        run: |
          echo "Environment variables loaded:"
          cut -d "=" -f1 .env

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Deploy with Docker Compose
        run: docker compose up -d