name: Deploy with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env file from GitHub secrets and vars
        run: |
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
          echo "MYSQL_DATABASE=${{ vars.MYSQL_DATABASE }}" >> .env
          echo "BACKEND_PORT=${{ vars.BACKEND_PORT }}" >> .env
          echo "BACKEND_HOST=${{ vars.BACKEND_HOST }}" >> .env
          echo "FRONTEND_PORT=${{ vars.FRONTEND_PORT }}" >> .env

      - name: Show .env file for debugging
        run: cat .env

      - name: Build and start containers
        run: docker compose --env-file .env up -d --build

      - name: Show MySQL logs if failure
        if: failure()
        run: |
          echo "=== MySQL Logs ==="
          docker logs mysql
