jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      MYSQL_DATABASE: ${{ vars.MYSQL_DATABASE }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}

    steps:
      - name: Show env variables
        run: |
          echo "MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD"
          echo "MYSQL_DATABASE: $MYSQL_DATABASE"
          echo "MYSQL_USER: $MYSQL_USER"
          echo "MYSQL_PASSWORD: $MYSQL_PASSWORD"
