name: Deploy with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production  # 👈 must match the environment name where your vars are set

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and start containers
        run: |
          MYSQL_ROOT_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD }}" \
          MYSQL_USER="${{ secrets.MYSQL_USER }}" \
          MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
          MYSQL_DATABASE="${{ vars.MYSQL_DATABASE }}" \
          BACKEND_PORT="${{ vars.BACKEND_PORT }}" \
          BACKEND_HOST="${{ vars.BACKEND_HOST }}" \
          FRONTEND_PORT="${{ vars.FRONTEND_PORT }}" \
          docker compose up -d --build

      - name: Show MySQL logs if failure
        if: failure()
        run: |
          echo "=== MySQL Logs ==="
          docker logs mysql
